version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
  
  web:
    image: alissondemys/rinha_dev:latest
    env_file: .env
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/usr/share/nginx/html/static
    ports:
      - 8087:80
    depends_on:
      - web

volumes:
  dbdata:
  static_volume: