version: '3'

services:
  web:
    image: wilsonsantosphx/rinhadev_mabel:latest
    command: >
          sh -c "
                python manage.py makemigrations && 
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  dbdata:
