# Generated by Django 5.0.1 on 2024-01-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.IntegerField()),
                ('url', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('languages', models.CharField(max_length=255)),
                ('commit_count', models.IntegerField()),
                ('line_count', models.IntegerField()),
                ('issues_count', models.IntegerField()),
                ('pulls_count', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
