# Generated by Django 5.0.1 on 2024-01-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='pulls_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
