# Generated by Django 5.0.1 on 2024-01-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0002_repositorio_pulls_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='url',
            field=models.URLField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
