# Generated by Django 5.0.1 on 2024-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0003_repositorio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='added_by',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
