# Generated by Django 5.0.1 on 2024-01-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0007_alter_repositorio_pontuacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositorio',
            old_name='pontuacao',
            new_name='score',
        ),
    ]
