# Generated by Django 5.0.1 on 2024-01-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0008_rename_pontuacao_repositorio_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='score',
            field=models.IntegerField(),
        ),
    ]
