# Generated by Django 5.0.1 on 2024-01-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='access_token',
            new_name='token',
        ),
    ]
