# Generated by Django 5.0.1 on 2024-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0010_alter_repositorio_added_by'),
        ('usuarios', '0002_rename_access_token_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='repositorios',
            field=models.ManyToManyField(to='repositorios.repositorio'),
        ),
    ]
